{% set base_name = "libignition-fuel-tools" %}
{% set version = "4.4.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-fuel-tools/archive/ignition-fuel-tools{{ major_version }}_{{ version }}.tar.gz
    sha256: aa888518a650ef68ce8c37d97f53c63861295e3b210a68b4be514a727b5ba228

build:
  number: 1
  skip: false
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config             # [not win]
  host:
    - libignition-msgs5
    - libignition-math6
    - libignition-common3
    - libignition-tools1
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/include/ignition/fuel_tools{{ major_version }}/ignition/fuel_tools.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\fuel_tools{{ major_version }}\ignition\fuel_tools.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-fuel-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Fuel Tools is composed by a client library and command line tools for interacting with Ignition Fuel servers.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
    - traversaro
